---
name: Egg-Model-DBIC
version: 2.03
author:
  - 'Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>'
abstract: DBIx::Class for Egg Model.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DBIx-Class: 0.07999
  DBIx::Class::Schema::Loader: 0.03
  Egg::Release: 2
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0
provides:
  Egg::Helper::Model::DBIC:
    file: lib/Egg/Helper/Model/DBIC.pm
    version: 2.00
  Egg::Model::DBIC:
    file: lib/Egg/Model/DBIC.pm
    version: 2.03
  Egg::Model::DBIC::Schema:
    file: lib/Egg/Model/DBIC/Schema.pm
    version: 2.00
  Egg::Plugin::DBIC::Transaction:
    file: lib/Egg/Plugin/DBIC/Transaction.pm
    version: 2.00
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
